import { business } from './data.js';
import { assetMetadata } from './asset-metadata.js';
export const arrow = '<span aria-hidden="true" class="arrow">↗</span>';
export const button = (text, href = '/contact#inquiry', variant = '') => `<a class="button ${variant}" href="${href}"><span>${text}</span>${arrow}</a>`;
export const label = text => `<p class="eyebrow">${text}</p>`;
export const heading = (lines, tag = 'h2', classes = '') => `<${tag} class="display ${classes}" data-reveal="lines">${lines.map(l => `<span class="line"><span>${l}</span></span>`).join('')}</${tag}>`;
export const photo = (file, alt, classes = '', eager = false) => `<div class="photo ${classes}" data-reveal="image"><picture><source type="image/avif" srcset="/assets/${file.replace('.webp', '-640.avif')} 640w, /assets/${file.replace('.webp', '.avif')} ${assetMetadata[file].width}w" sizes="(max-width: 767px) 100vw, 50vw" /><img src="/assets/${file}" srcset="/assets/${file.replace('.webp', '-640.webp')} 640w, /assets/${file} ${assetMetadata[file].width}w" sizes="(max-width: 767px) 100vw, 50vw" alt="${alt}" width="${assetMetadata[file].width}" height="${assetMetadata[file].height}" loading="${eager ? 'eager' : 'lazy'}" decoding="async" ${eager ? 'fetchpriority="high"' : ''} /></picture></div>`;
export function header(active) {
  const links = [['/', 'Home', 'home'], ['/menu', 'Menu', 'menu'], ['/contact', 'Contact & pricing', 'contact']];
  return `<header class="header"><a href="/" class="brand" aria-label="Sol & Citrus home"><img src="/assets/logo.webp" alt="Sol & Citrus original logo" width="66" height="66" /><span class="brand-tag">CRAFTED BEVERAGES<br />MEMORABLE EXPERIENCES</span></a><nav class="desktop-nav" aria-label="Main navigation">${links.map(([href, text, id]) => `<a href="${href}" ${active === id ? 'aria-current="page"' : ''}>${text}</a>`).join('')}</nav>${button('Book an event', '/contact#inquiry', 'header-cta')}<button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open navigation"><span></span><span></span></button></header>
  <dialog id="mobile-menu" class="mobile-menu" aria-label="Navigation"><div class="mobile-menu-top"><img src="/assets/logo.webp" alt="Sol & Citrus" width="64" height="64" /><button class="menu-close" aria-label="Close navigation">✕</button></div><nav aria-label="Mobile navigation">${links.map(([href, text, id]) => `<a href="${href}" ${active === id ? 'aria-current="page"' : ''}>${text}${arrow}</a>`).join('')}</nav>${button('Book an event')}<div class="mobile-contact">${label('Miami & South Florida')}<a href="mailto:${business.email}">${business.email}</a><a href="${business.instagram}" target="_blank" rel="noopener noreferrer">Instagram ${arrow}</a></div></dialog>`;
}
export function footer() {
  return `<footer class="footer"><div class="footer-top"><a href="/" class="footer-brand"><img src="/assets/logo.webp" alt="Sol & Citrus" width="104" height="104" /></a><p class="footer-position">Premium Mobile Beverage Experiences<br />in Miami & South Florida</p><div>${label('Say hello')}<a href="mailto:${business.email}">${business.email}</a><a href="tel:+13054500711">${business.phone}</a></div><div>${label('Stay connected')}<a href="${business.instagram}" target="_blank" rel="noopener noreferrer">Instagram ${arrow}</a><a href="${business.tiktok}" target="_blank" rel="noopener noreferrer">TikTok ${arrow}</a><a href="${business.facebook}" target="_blank" rel="noopener noreferrer">Facebook ${arrow}</a></div></div><div class="footer-statement">A little citrus. A lot of <em>sunshine.</em></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} SC HOSPITALITY LLC.</span><nav aria-label="Footer navigation"><a href="/">Home</a><a href="/menu">Menu</a><a href="/contact">Contact & pricing</a></nav><nav aria-label="Legal"><a href="/privacy-policy">Privacy policy</a><a href="/terms-of-service">Terms of service</a><a href="/accessibility-statement">Accessibility</a></nav><a href="#" class="back-top" aria-label="Back to top">↑</a></div></footer>`;
}
export function closing() {
  return `<section class="closing">${photo('banner.webp', 'Original Sol & Citrus beverage bar surrounded by South Florida palms')}<div class="closing-content">${label('Your occasion. Our craft.')}${heading(['Book your', '<em>experience.</em>'])}<p>Planning a wedding, private celebration, corporate gathering or community event? Let’s create a beverage experience around it.</p>${button('Request a quote', '/contact#inquiry', 'light')}</div></section>`;
}
